# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8497ba6fe885f833cc851f6c4a0bc6ab1043a513e02cdbe09ed827fba1db09538fc8877c6158762301e8c5708af812d5fc77546d470813758a8026b880396af

test:
  secret_key_base: 8883c3f8b0163592035ff4a465be6503386e782f04c998aae554724fb114c993c1ef81620822a4b63778f1fce15bd7ce81759e74cee871a00228d0d13d043b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
